### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by balasivagnanam** [magr0s/vue-grapesjs#8]
Hi, I am trying to create drag and drop of components with VueJS and GrapesJS. Was trying to find a starting point.Found this repo.

it says plugin for GrapesJS. How to use this and how to make it work along with GrapesJS?

Thanks

**Comment by magr0s** [comment]
Hi. See,
https://github.com/magr0s/vue-grapesjs/blob/master/src/main.js#L3
https://github.com/magr0s/vue-grapesjs/blob/master/src/App.vue

**Comment by joshk132** [comment]
Hi, I am having the same issue, I can't get it to work. I copied the main.js and App.vue files directly and changed out the import for grape js to use the npm package installed however when I run npm serve it shows a blank page. Is there more settings I need than the basics shown in the above files? What am I missing that will now allow this to show up? Is it a grapejs thing or something related to this package?
