### ISSUE TITLE
 Unknown custom element: <grapesjs>

### ISSUE THREAD

**Issue by mtrnik** [magr0s/vue-grapesjs#9]
Hi i cloned your repository, installed dependencies and run 'npm run serve'
when i go to the browser, I see just blank page and in console there is bug:

 [Vue warn]: Unknown custom element: <grapesjs> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <App> at src/App.vue
       <Root> vue.runtime.esm.js:619
    VueJS 21
    <anonymous> main.js:9
    js app.js:2497
    __webpack_require__ app.js:724
    fn app.js:101
    0 app.js:2510
    __webpack_require__ app.js:724
    <anonymous> app.js:791
    <anonymous> app.js:794

What could be a problem?

**Comment by j2l** [comment]
Hello,
Same problem for me :(
Did you fix it?
@mtrnik @magr0s

**Comment by mtrnik** [comment]
> Hello,
> Same problem for me :(
> Did you fix it?
> @mtrnik @magr0s

No, I was not able to fix it, however there is a possibility to use grapesjs in vue without this plugin. 
There are some discussions how to do it at grapesjs github channel. Good starting point for me was this issue: [https://github.com/artf/grapesjs/issues/27](https://github.com/artf/grapesjs/issues/275)

**Comment by j2l** [comment]
Thanks!
